spring:
  profiles:
    active: dev

---
server:
  port: 7001
spring:
  profiles: dev
  application:
    name: springcloud-config-eureka
# eureka
#eureka 配置
eureka:
  instance:
    hostname: eureka7001.com #eureka 服务端的实例名称
  client:
    service-url:
      #单机
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka
    register-with-eureka: false # 表示是否向eureka注册中心注册自己
    fetch-registry: false #false 代表自己为注册中心

---
server:
  port: 7001
spring:
  profiles: test
  application:
    name: springcloud-config-eureka
# eureka
#eureka 配置
eureka:
  instance:
    hostname: eureka7001.com #eureka 服务端的实例名称
  client:
    service-url:
      #单机
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka
    register-with-eureka: false # 表示是否向eureka注册中心注册自己
    fetch-registry: false #false 代表自己为注册中心
